### PR TITLE
Adding TSR as requirement for everything with  prpy

### PR DESCRIPTION
**Pull request by Shushman**

### CODE REVIEW

**Comment by jslee02** [comment]
Out of curiosity, I don't know much about how rosinstall works, but `tsr` shouldn't be installed automatically when `prpy` is installed (since `tsr` is a dependency of `prpy`)?

**Comment by brianhou** [comment]
I'm not familiar with this either (perhaps @mkoval might be able to shed some light on how it works?) although I noticed that both `prpy` and `herbpy` are listed in a [rosinstall](https://github.com/personalrobotics/pr-rosinstalls/blob/master/herb-minimal-sim.rosinstall) even though `prpy` is a dependency of `herbpy`.

**Comment by Shushman** [comment]
To the best of my knowledge, it will be **built** automatically while building `prpy` in the workspace but that's only if it is there already. For the package to be cloned while setting up the workspace it needs to be in the `rosinstall` file so it is pulled and then updated when you run `wstool up`.

**Comment by mkoval** [comment]
@Shushman's explanation is correct. The dependencies in `package.xml` file are also used to:

1. constrain the order that packages are built in
2. generate dependencies of Debian packages built from the ROS packages
3. controls what packages are installed on Travis, via the `distribution.yaml` file

Building `.deb`s from our packages is more trouble than it's worth (@psigen and I spent _a lot_ of time on this) without using the ROS buildfarm (which has it's own issues). In principle, we could use the same infrastructure as (3) to generate these `.rosinstall` files, but that is also annoying in practice.

So...the easiest solution is to simply update these `.rosinstall` files when our dependencies change.

**Pull request merged**
