### PR TITLE
Replaced references to old branches that were merged into master

### PR DESCRIPTION
**Pull request by amalnanavati**
On multiple branches, summer 2019 demo branches were merged into master, resulting in the rosinstall breaking. Fixed that my setting the version of those branches to 'master'.

### CODE REVIEW

**Comment by amalnanavati** [comment]
@egordon FYI, I wanted to flag that the pr-rosinstalls repo is public, but the following repos are private: pose_estimators, food_detector, face_detection. Perhaps we should (eventually) make them all public?

**Comment by amalnanavati** [comment]
Actually don't merge it in yet, I believe some new packages need to be added. I'll comment when I have fully gotten sim to run.

**Comment by amalnanavati** [comment]
Ready for review -- I verified that the simulation, as installed by these files, works on my computer :)

**Comment by amalnanavati** [comment]
Actually, I'm wondering whether the demo/summer2019 branch is still the correct branch for some of these, or if we should use another branch (e.g., the [food_detector](https://github.com/personalrobotics/food_detector) repo has a `demo/fall2020` branch, as well as its master branch). 

Let's hold off on merging until we discuss which branches we want to be used.

**Review by egordon — DISMISSED** [review]
All branches can be changed to master.

**Comment by amalnanavati** [comment]
https://github.com/personalrobotics/face_detection need to be made public

**Comment by egordon** [comment]
Neither do I, since it's a fork. Asking @tapomayukh  to make https://github.com/tapomayukh/face_detection public.

**Comment by egordon** [comment]
@amalnanavati face_detection visibility changed! All branches can now be changed to master and I can re-review.

**Review by egordon — APPROVED** [review]
Great, thank you!

**Pull request merged**
